services:
  - type: worker
    name: treino-modelo
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python treino_continuo.py
    schedule: "0 3 * * *"  # corre todos os dias às 03:00 UTC
    envVars:
      - key: FIREBASE_JSON
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
